apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-ingress
spec:
  rules:
  # - host: www.liwenqiang.site
  #   http:
  #     paths:
  #     - pathType: Prefix
  #       path: "/"
  #       backend:
  #         service:
  #           name: nginx-app
  #           port:
  #             number: 80
  - host: golang.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: simple-golang
            port:
              number: 80
  # - host: node.liwenqiang.site
  #   http:
  #     paths:
  #     - pathType: Prefix
  #       path: "/"
  #       backend:
  #         service:
  #           name: simple-node
  #           port:
  #             number: 80
