apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: host-ingress
spec: 
  ingressClassName: contour
  rules:
  - host: www.liwenqiang.site
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: simple-golang
            port:
              number: 80
  # - host: node.example.com
  #   http:
  #     paths:
  #     - pathType: Prefix
  #       path: /
  #       backend:
  #         service:
  #           name: simple-node
  #           port:
  #             number: 80

