apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    run: nginx-app
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
        run: nginx-app
  template:
    metadata:
        labels:
          run: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: nginx:alpine
        ports:
          - containerPort: 80