apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node
  labels:
    run: simple-node
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
        run: simple-node
  template:
    metadata:
        labels:
          run: simple-node
    spec:
      containers:
      - name: simple-node
        image: zooeymoon1989/simple-node:latest
        ports:
          - containerPort: 3000