apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-golang
  labels:
    run: simple-golang
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
        run: simple-golang
  template:
    metadata:
        labels:
          run: simple-golang
    spec:
      containers:
      - name: simple-golang
        image: zooeymoon1989/simple-golang:latest
        ports:
          - containerPort: 3000