apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-golang-deployment
  labels:
    app: simple-golang
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-golang
  template:
    metadata:
      labels:
        app: simple-golang
    spec:
      containers:
      - name: simple-golang
        image: zooeymoon1989/simple-golang:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: simple-golang-service
spec:
  selector:
    app: simple-golang
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP