apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpaca-prod
  labels:
    ver: "1"
    app: alpaca
    env: prod
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      ver: "1"
      app: alpaca
      env: prod
  template:
    metadata:
      labels:
        ver: "1"
        app: alpaca
        env: prod
    spec:
      containers:
      - name: alpaca-prod
        image: gcr.io/kuar-demo/kuard-amd64:blue
        ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: alpaca-prod
  annotations:
    service.kubernetes.io/qcloud-loadbalancer-internal-subnetid: subnet-xxxxx
  labels:
    ver: "1"
    app: alpaca
    env: prod
spec:
  selector:
    ver: "1"
    app: alpaca
    env: prod
  ports:
  - name: alpaca-pod
    protocol: TCP
    port: 48858
    targetPort: 8080