apiVersion: apps/v1
kind: Deployment
metadata:
  name: bandicoot-prod
  labels:
    ver: "2"
    app: bandicoot
    env: prod
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      ver: "2"
      app: bandicoot
      env: prod
  template:
    metadata:
      labels:
        ver: "2"
        app: bandicoot
        env: prod
    spec:
      containers:
      - name: bandicoot-prod
        image: jmutai/kuard-amd64
        ports:
        - containerPort: 8080