---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-gw-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-gateway-role
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "secrets", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources:
      - "gatewayclasses"
      - "gateways"
      - "httproutes"
      - "grpcroutes"
      - "tcproutes"
      - "tlsroutes"
      - "referencegrants"
      # - "backendtlspolicies"
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-gateway-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-gateway-role
subjects:
  - kind: ServiceAccount
    name: traefik-gw-sa
    namespace: default