apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simple-node
  labels:
    run: simple-node
    version: "1"
spec:
# modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      run: simple-node
      version: "1"
  template:
    metadata:
      labels:
        run: simple-node
        version: "1"
    spec:
      containers:
      - name: simple-node
        image: zooeymoon1989/simple-node:latest
        ports:
        - containerPort: 3000
        
