apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simple-golang
  labels:
    run: simple-golang
    version: "1"
spec:
# modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      run: simple-golang
      version: "1"
  template:
    metadata:
      labels:
        run: simple-golang
        version: "1"
    spec:
      containers:
      - name: simple-golang
        image: zooeymoon1989/simple-golang:latest
        ports:
        - containerPort: 3000
        
