apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 3
  selector:
    matchLabels:
      app: mongo

  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        storageClassName: longhorn
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
  template:
    metadata:
      labels:
        app: mongo
    spec:
      initContainers:
      - name: init-mongo
        image: mongo
        command:
          - /bin/bash
          - /config/init.sh
        volumeMounts:
        - name: config
          mountPath: /config
      containers:
      - name: mongodb
        image: mongo
        command:
        - mongod
        - --replSet
        - rs0
        - --bind_ip_all
        ports:
        - containerPort: 27017
          name: peer
        volumeMounts:
        - name: config
          mountPath: /config
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: config
        configMap:
          name: mongo-init
    