apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-golang
  namespace: default
spec:
  replicas: 9
  selector:
    matchLabels:
      app: simple-golang
  template:
    metadata:
      labels:
        app: simple-golang
    spec:
      containers:
      - name: simple-golang
        image: zooeymoon1989/simple-node
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-golang
  namespace: default
spec:
  selector:
    app: simple-golang
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80