apiVersion: v1
kind: Pod
metadata:
  name: amicontained
spec:
  containers:
  - name: amicontained
    image: r.j3ss.co/amicontained
    command: [ "/bin/sh", "-c","--" ]
    args:
      - amicontained
