apiVersion: v1
kind: Pod
metadata:
  name: amicontained
spec:
  containers:
  - name: amicontained
    image: jess/amicontained:v0.4.9
    command: [ "/bin/sh", "-c","--" ]
    args:
      - amicontained
