apiVersion: v1
kind: Service
metadata:
  labels:
    app: work-queue
    component: queue
    chapter: jobs
  name: queue
spec:
  selector:
    run: work-queue
    component: queue
  ports: 
  - protocol: TCP
    port: 8080
    targetPort: 8080