apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  labels:
    run: kafka-ui
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
        run: kafka-ui
  template:
    metadata:
        labels:
          run: kafka-ui
    spec:
      containers:
      - name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        ports:
          - containerPort: 8080
        env: 
         - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
           value: kafka.liwenqiang.site:9092

--- 

apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
spec:
  type: ClusterIP
  selector:
    run: kafka-ui
  ports:
  - name: kafka-ui
    protocol: TCP
    port: 8080
    targetPort: 8080