apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-gw-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-gateway-role
rules:
  # Gateway API 相关
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gateways","gatewayclasses","httproutes","grpcroutes","tcproutes","udproutes","referencegrants"]
    verbs: ["get","list","watch"]

  # Core API
  - apiGroups: [""]
    resources: ["services","pods","namespaces","secrets","endpoints"]
    verbs: ["get","list","watch"]

  # EndpointSlice (Service发现)
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-gateway-rb
subjects:
  - kind: ServiceAccount
    name: traefik-gw-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: traefik-gateway-role
  apiGroup: rbac.authorization.k8s.io