apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-gateway-role
rules:
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gateways","gatewayclasses","httproutes"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["services","endpoints","pods","namespaces"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-gateway-rb
subjects:
  - kind: ServiceAccount
    name: traefik-gw-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: traefik-gateway-role
  apiGroup: rbac.authorization.k8s.io