apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-gw-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-gateway-role
rules:
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gatewayclasses","gateways","httproutes","referencegrants","grpcroutes","tcproutes","udproutes"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["services","endpoints","pods","namespaces","secrets"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-gateway-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-gateway-role
subjects:
- kind: ServiceAccount
  name: traefik-gw-sa
  namespace: default