---
- hosts: all
  become: yes
  tasks:

    - name: delete golang sdk files
      ansible.builtin.file:
        path: /usr/local/go
        state: absent

    - name: download golang sdk files
      ansible.builtin.get_url:
        url: https://go.dev/dl/go1.20.linux-amd64.tar.gz
        dest: ~/
        force_basic_auth: yes

    - name: Recursively remove golang 
      ansible.builtin.file:
        path: /usr/local/go
        state: absent

    - name: unarchive tar file to /usr/local
      unarchive:
        src: ~/go1.20.linux-amd64.tar.gz
        dest: /usr/local
        remote_src: yes
    
    - name: export PATH=$PATH:/usr/local/go/bin
      ansible.builtin.shell:
        cmd: echo export PATH=$PATH:/usr/local/go/bin >> ~/.profile

    - name: remove golang tar file
      ansible.builtin.file:
        path: ~/go1.20.linux-amd64.tar.gz
        state: absent
