---
- hosts: all
  become: yes
  tasks:
    - name: get git repo
      shell: git clone https://github.com/Mirantis/cri-dockerd.git
    - name: cd 
      shell: cd cri-dockerd
    - name: go build 
      shell: go build -o bin/cri-dockerd
    - name: make dir
      shell: mkdir -p /usr/local/bin
    - name: install cri-docker
      shell: sudo install -o root -g root -m 0755 bin/cri-dockerd /usr/local/bin/cri-dockerd
    - name: cp systemd/*
      shell: sudo cp -a packaging/systemd/* /etc/systemd/system
    - name: sed
      shell: sudo sed -i -e 's,/usr/bin/cri-dockerd,/usr/local/bin/cri-dockerd,' /etc/systemd/system/cri-docker.service
    - name: daemon-reload
      shell: sudo systemctl daemon-reload
    - name: enable cri-docker.service
      shell: sudo systemctl enable cri-docker.service
    - name:  enable --now cri-docker.socket
      shell: sudo systemctl enable --now cri-docker.socket