---
- hosts: all
  become: yes
  tasks:
    - name: install jdk11
      ansible.builtin.apt:
        name:
            - default-jre
        update_cache: true
    - name: install default-jdk
      ansible.builtin.apt:
        name:
            - default-jdk
        update_cache: true