---
- hosts: control_plane
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: workers
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars['control1'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt

# sudo kubeadm join 10.0.0.14:6443 --token iid2c6.1t4ovjnjmunju525 \
# --discovery-token-ca-cert-hash sha256:af96659c34caff3d50b604f73002fe42fa639f35914d8d301486cd55853437fa \
# --cri-socket=unix:///var/run/cri-dockerd.sock